default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: user
      password: user
      dbname: user
      schema: public
      threads: 1
      port: 5431
